export default [
  {
    themeId: "1653",
    coinItemId: null,
    name: "锤子便签主题第2版",
    cover: "https://files.mdnice.com/pic/c781d9a9-6116-4f60-9eac-f2132844b73d.png",
    css:
      "/* 自定义样式，实时生效，浏览器实时缓存 */\n\n/* 全局属性\n * 页边距 padding: 30px;\n * 全文字体 font-family: ptima-Regular;\n * 英文换行 word-break: break-all;\n */\n\n.nice-wx-box{\n  padding: 0;\n  margin:0;\n}\n\n#nice {\n  background-color: #fbf7ee;\n    /* 注：请在大括号内改写！！！ */\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial,\n  'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol',\n  'Noto Color Emoji' !important;\n  color: #635753 !important;\n  padding: 10px 10px;\n}\n\n/* 段落，下方未标注标签参数均同此处\n * 上边距 margin-top: 5px;\n * 下边距 margin-bottom: 5px;\n * 行高 line-height: 26px;\n * 词间距 word-spacing: 3px;\n * 字间距 letter-spacing: 3px;\n * 对齐 text-align: left;\n * 颜色 color: #3e3e3e;\n * 字体大小 font-size: 16px;\n * 首行缩进 text-indent: 2em;\n */\n#nice p {\n  \tcolor: #635753;\n    /* 注：请在大括号内改写！！！ */\n  line-height: 2\n}\n\n/* 一级标题 */\n#nice h1 {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 一级标题内容 */\n#nice h1 .content {\n  color: #635753;\n    /* 注：请在大括号内改写！！！ */\n}\n\n/* 一级标题前缀 */\n#nice h1 .prefix {\n  color: #635753;\n    /* 注：请在大括号内改写！！！ */\n}\n\n/* 一级标题后缀 */\n#nice h1 .suffix {\n  color: #635753;\n    /* 注：请在大括号内改写！！！ */\n}\n\n/* 二级标题 */\n#nice h2 {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 二级标题内容 */\n#nice h2 .content {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 二级标题前缀 */\n#nice h2 .prefix {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 二级标题后缀 */\n#nice h2 .suffix {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 三级标题 */\n#nice h3 {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 三级标题内容 */\n#nice h3 .content {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 三级标题前缀 */\n#nice h3 .prefix {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 三级标题后缀 */\n#nice h3 .suffix {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 无序列表整体样式\n * list-style-type: square|circle|disc;\n */\n#nice ul {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 有序列表整体样式\n * list-style-type: upper-roman|lower-greek|lower-alpha;\n */\n#nice ol {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 列表内容，不要设置li\n */\n#nice li section {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 一级引用\n * 左边缘颜色 border-left-color: black;\n * 背景色 background: gray;\n */\n#nice .multiquote-1 {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 一级引用文字 */\n#nice .multiquote-1 p {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 二级引用\n */\n#nice .multiquote-2 {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 二级引用文字 */\n#nice .multiquote-2 p {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 三级引用\n */\n#nice .multiquote-3 {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 三级引用文字 */\n#nice .multiquote-3 p {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 链接 \n * border-bottom: 1px solid #009688;\n */\n#nice a {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n  border-bottom: 1px solid #ebdfd5;\n}\n\n/* 加粗 */\n#nice strong {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 斜体 */\n#nice em {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 加粗斜体 */\n#nice em strong {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 删除线 */\n#nice del {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 分隔线\n * 粗细、样式和颜色\n * border-top: 1px solid #3e3e3e;\n */\n#nice hr {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 图片\n * 宽度 width: 80%;\n * 居中 margin: 0 auto;\n * 居左 margin: 0 0;\n */\n#nice img {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 行内代码 */\n#nice p code, #nice li code {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n \n}\n\n/* \n * 代码块不换行 display: -webkit-box !important;\n * 代码块换行 display: block;\n */\n#nice pre code {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n  \n}\n\n/*\n * 表格内的单元格\n * 字体大小 font-size: 16px;\n * 边框 border: 1px solid #ccc;\n * 内边距 padding: 5px 10px;\n */\n#nice table tr th,\n#nice table tr td {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* \n * 某一列表格列宽控制\n * n 可以修改为具体数字，不修改时表示所有列\n * 最小列宽 min-width: 85px;\n */\n#nice table tr th:nth-of-type(n),\n#nice table tr td:nth-of-type(n){\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 脚注文字 */\n#nice .footnote-word {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 脚注上标 */\n#nice .footnote-ref {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* \"参考资料\"四个字 \n * 内容 content: \"参考资料\";\n */\n#nice .footnotes-sep:before {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 参考资料编号 */\n#nice .footnote-num {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 参考资料文字 */\n#nice .footnote-item p { \n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 参考资料解释 */\n#nice .footnote-item p em {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 行间公式\n * 最大宽度 max-width: 300% !important;\n */\n#nice .block-equation svg {\n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\n/* 行内公式\n */\n#nice .inline-equation svg {  \n    /* 注：请在大括号内改写！！！ */\n  color: #635753;\n}\n\nimg{\n  width: 100%;\n  box-shadow: 14px 14px 28px #e6e6e6, -14px -14px 28px #fff;\n  border: 9px solid #ffffff;\n  outline: 1px solid #ebdfd5;\n\n}\n\n.custom::before {\n background-color: #fbf7ee !important;\n  \n}\n\ncode {\n  background-color: #fbf7ee !important;\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial,\n  'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol',\n  'Noto Color Emoji' !important;\n}",
    article: "https://mp.weixin.qq.com/s/sqP9w3LU7eNZ9uq5MC0JDA",
    html: null,
    exampleHtml: null,
    authorId: null,
    authorName: "老法师昭昭",
    authorEmail: null,
    description: "锤子便签主题：不要因为走的太远，就忘记了为什么出发",
    sort: null,
    checked: true,
    userThemeId: 48049,
    userThemeType: 0,
    fixThemeId: null,
    price: null,
    tmpPrice: 200,
    isPublic: true,
    createTime: "2021-06-04T10:26:24.000+0800",
    updateTime: "2021-06-15T12:01:14.000+0800",
  },
  {
    themeId: "1348",
    coinItemId: null,
    name: "雁栖湖",
    cover: "https://files.mdnice.com/pic/af325a49-1e79-4a50-be03-ea24a4d88720.png",
    css:
      '/* 全局属性\n * 页边距 padding: 30px;\n * 全文字体 font-family: ptima-Regular;\n * 英文换行 word-break: break-all;\n */\n#nice {\n  counter-reset: counterh1 counterh2 counterh3;\n}\n\n/* 段落，下方未标注标签参数均同此处\n * 上边距 margin-top: 5px;\n * 下边距 margin-bottom: 5px;\n * 行高 line-height: 26px;\n * 词间距 word-spacing: 3px;\n * 字间距 letter-spacing: 3px;\n * 对齐 text-align: left;\n * 颜色 color: #3e3e3e;\n * 字体大小 font-size: 16px;\n * 首行缩进 text-indent: 2em;\n */\n#nice p {\n}\n\n/* 一级标题 */\n#nice h1 {\n  line-height: 28px;\n  border-bottom: 1px solid rgb(37,132,181);\n}\n\n#nice h1:before {\n  background: rgb(37,132,181);\n  color: white;\n  counter-increment: counterh1;\n  content: \'Part\'counter(counterh1); \n  padding: 2px 8px;\n}\n\n/* 一级标题内容 */\n#nice h1 .content {\n  color: rgb(37,132,181);\n  margin-left: 8px;\n  font-size: 20px;\n}\n\n/* 一级标题前缀 */\n#nice h1 .prefix {\n}\n\n/* 一级标题后缀 */\n#nice h1 .suffix {\n}\n\n/* 二级标题 */\n#nice h2 {\n}\n\n/* 二级标题内容 */\n#nice h2 .content {\n  font-size: 18px;\n  border-bottom: 4px solid rgb(37,132,181);\n  padding: 2px 4px;\n  color: rgb(37,132,181);\n}\n\n/* 二级标题前缀 */\n#nice h2 .prefix {\n  display: inline-block;\n}\n\n#nice h2 .prefix:before {\n  counter-increment: counterh2;\n  content: counter(counterh2); \n  color:rgb(159,205,208);\n  border-bottom: 4px solid rgb(159,205,208);\n  font-size: 18px;\n  padding: 2px 4px;\n}\n\n/* 二级标题后缀 */\n#nice h2 .suffix {\n}\n\n/* 三级标题 */\n#nice h3 {\n}\n\n/* 三级标题内容 */\n#nice h3 .content {\n  font-size: 16px;\n  border-bottom: 1px solid rgb(37,132,181);\n  padding: 2px 10px;\n  color: rgb(37,132,181);\n}\n\n/* 三级标题前缀 */\n#nice h3 .prefix {\n  display:inline-block;\n  background:linear-gradient(45deg, transparent 48%, rgb(37,132,181) 48%, \n            rgb(37,132,181) 52%, transparent 52%);\n  width:24px;\n  height:24px;\n  margin-bottom: -7px;\n}\n\n/* 三级标题后缀 */\n#nice h3 .suffix {\n}\n\n/* 无序列表整体样式\n * list-style-type: square|circle|disc;\n */\n#nice ul {\n}\n\n/* 有序列表整体样式\n * list-style-type: upper-roman|lower-greek|lower-alpha;\n */\n#nice ol {\n}\n\n/* 列表内容，不要设置li\n */\n#nice li section {\n}\n\n/* 一级引用\n * 左边缘颜色 border-left-color: black;\n * 背景色 background: gray;\n */\n#nice .multiquote-1 {\n  border: 1px dashed rgb(37,132,181);\n  background: transparent;\n}\n\n/* 一级引用文字 */\n#nice .multiquote-1 p {\n}\n\n/* 二级引用\n */\n#nice .multiquote-2 {\n  border: 1px dashed rgb(248,99,77);\n  box-shadow: none;\n}\n\n#nice .multiquote-2 blockquote {\n  margin: 0;\n}\n\n/* 二级引用文字 */\n#nice .multiquote-2 p {\n}\n\n#nice .multiquote-2 strong {\n  color:rgb(248,99,77);\n}\n\n#nice .multiquote-2 a {\n  color:rgb(248,99,77);\n  border-bottom: 1px solid rgb(248,99,77);\n}\n\n/* 三级引用\n */\n#nice .multiquote-3 {\n}\n\n/* 三级引用文字 */\n#nice .multiquote-3 p {\n}\n\n/* 链接 \n * border-bottom: 1px solid #009688;\n */\n#nice a {\n  color:rgb(37,132,181);\n  border-bottom: 1px solid rgb(37,132,181);\n}\n\n/* 加粗 */\n#nice strong {\n  color: rgb(37,132,181);\n}\n\n/* 斜体 */\n#nice em {\n  color: rgb(37,132,181);\n}\n\n/* 加粗斜体 */\n#nice em strong {\n  color: rgb(37,132,181);\n}\n\n/* 删除线 */\n#nice del {\n}\n\n/* 分隔线\n* 粗细、样式和颜色\n* border-top: 1px solid #3e3e3e;\n*/\n#nice hr {\n  border-top: 1px solid rgb(37,132,181);\n}\n\n/* 图片\n* 宽度 width: 80%;\n* 居中 margin: 0 auto;\n* 居左 margin: 0 0;\n*/\n#nice img {\n}\n\n/* 图片描述文字 */\n#nice figcaption {\n}\n\n/* 行内代码 */\n#nice p code, #nice li code {\n}\n\n/* \n * 代码块不换行 display: -webkit-box !important;\n * 代码块换行 display: block;\n */\n#nice pre code {\n}\n\n/*\n * 表格内的单元格\n * 字体大小 font-size: 16px;\n * 边框 border: 1px solid #ccc;\n * 内边距 padding: 5px 10px;\n */\n#nice table tr th {\n  border: 1px solid rgb(248,99,77);\n  background-color: rgb(235,114, 80);\n  color: #f8f8f8;\n  border-bottom: 0;\n  border: 1px solid rgb(245,203,174);\n}\n\n#nice table tr td {\n  border: 1px solid rgb(245,203,174);\n}\n/* \n * 某一列表格列宽控制\n * n 可以修改为具体数字，不修改时表示所有列\n * 最小列宽 min-width: 85px;\n */\n#nice table tr th:nth-of-type(n),\n#nice table tr td:nth-of-type(n){\n}\n\n#nice table tr:nth-of-type(2) {\n  background-color: rgb(248,222,203);\n}\n/* 脚注文字 */\n#nice .footnote-word {\n  color:rgb(37,132,181);\n}\n\n/* 脚注上标 */\n#nice .footnote-ref {\n  color:rgb(37,132,181);\n}\n\n/* "参考资料"四个字 \n * 内容 content: "参考资料";\n */\n#nice .footnotes-sep:before {\n}\n\n/* 参考资料编号 */\n#nice .footnote-num {\n}\n\n/* 参考资料文字 */\n#nice .footnote-item p { \n}\n\n/* 参考资料解释 */\n#nice .footnote-item p em {\n}\n\n/* 行间公式\n * 最大宽度 max-width: 300% !important;\n */\n#nice .block-equation svg {\n}\n\n/* 行内公式\n */\n#nice .inline-equation svg { \n}',
    article: "https://mp.weixin.qq.com/s/bCDv3zI85qO8Gu9H9v5pag",
    html: null,
    exampleHtml: null,
    authorId: null,
    authorName: "画手大鹏",
    authorEmail: null,
    description: "作者于中国科学院大学雁栖湖校区上学时排版的一篇文章，故而取名雁栖湖",
    sort: 1,
    checked: true,
    userThemeId: 63140,
    userThemeType: 0,
    fixThemeId: null,
    price: null,
    tmpPrice: 0,
    isPublic: true,
    createTime: "2021-04-02T11:50:14.000+0800",
    updateTime: "2021-04-02T11:51:51.000+0800",
  },
  {
    themeId: "62",
    coinItemId: null,
    name: "WeChat-Format",
    cover: "https://files.mdnice.com/pic/7c426155-27e8-493b-a483-ce966884a8b9.png",
    css:
      '/* 全局属性\n * 页边距 padding: 30px;\n * 全文字体 font-family: ptima-Regular;\n * 英文换行 word-break: break-all;\n */\n#nice {\n}\n\n/* 段落，下方未标注标签参数均同此处\n * 上边距 margin-top: 5px;\n * 下边距 margin-bottom: 5px;\n * 行高 line-height: 26px;\n * 词间距 word-spacing: 3px;\n * 字间距 letter-spacing: 3px;\n * 对齐 text-align: left;\n * 颜色 color: #3e3e3e;\n * 字体大小 font-size: 16px;\n * 首行缩进 text-indent: 2em;\n */\n#nice p {\n  line-height: 1.6;\n  color: #3f3f3f;\n  font-size: 16px;\n  margin: 10px 0px;\n}\n\n/* 一级标题 */\n#nice h1 {\n}\n\n/* 一级标题内容 */\n#nice h1 .content {\n}\n\n/* 一级标题修饰 请参考有实例的主题 */\n#nice h1:after {\n}\n\n/* 二级标题 */\n#nice h2 {\n  margin: 80px 10px 40px 10px;\n  text-align: center;\n  font-weight: normal;\n  color: #3f3f3f;\n  font-size: 140%;\n}\n\n/* 二级标题内容 */\n#nice h2 .content {\n}\n\n/* 二级标题修饰 请参考有实例的主题 */\n#nice h2:after {\n}\n\n/* 三级标题 */\n#nice h3 {\n  margin: 40px 0px 20px 0px;\n  font-weight: bold;\n  line-height: 1.5;\n  color: #3f3f3f;\n  font-size: 120%;\n}\n\n/* 三级标题内容 */\n#nice h3 .content {\n}\n\n/* 三级标题修饰 请参考有实例的主题 */\n#nice h3:after {\n}\n\n/* 无序列表整体样式\n * list-style-type: square|circle|disc;\n */\n#nice ul {\n}\n\n/* 有序列表整体样式\n * list-style-type: upper-roman|lower-greek|lower-alpha;\n */\n#nice ol {\n}\n\n/* 列表内容，不要设置li\n */\n#nice li section {\n}\n\n/* 引用\n* 左边缘颜色 border-left-color: black;\n* 背景色 background: gray;\n*/\n#nice .multiquote-1 {\n  color: rgb(91,91,91);\n  border-left: 3px solid rgb(158,158,158);\n  background: rgba(158, 158, 158, 0.1);\n  padding: 1px 0 1px 10px;\n  margin: 20px 0px;\n}\n\n/* 引用文字 */\n#nice .multiquote-1 p {\n  color: #3f3f3f;\n  line-height: 1.5;\n  font-size: 16px;\n  margin: 10px;\n  padding: 0px;\n}\n\n/* 链接 \n * border-bottom: 1px solid #009688;\n */\n#nice a {\n  color: #ff3502;\n  border-bottom: 1px solid #ff3502;\n}\n\n/* 加粗 */\n#nice strong {\n  color: #ff3502;\n  line-height: 1.5;\n  font-size: 16px;\n}\n\n/* 斜体 */\n#nice em {\n}\n\n/* 加粗斜体 */\n#nice em strong {\n}\n\n/* 删除线 */\n#nice del {\n}\n\n/* 分隔线\n* 粗细、样式和颜色\n* border-top: 1px solid #3e3e3e;\n*/\n#nice hr {\n}\n\n/* 图片\n* 宽度 width: 80%;\n* 居中 margin: 0 auto;\n* 居左 margin: 0 0;\n*/\n#nice img {\n}\n\n/* 图片描述文字 */\n#nice figcaption {\n}\n\n/* 行内代码 */\n#nice p code, #nice li code {\n  background: #f8f5ec;\n  color: #ff3502;\n  line-height: 1.5;\n  font-size: 90%;\n  padding: 3px 5px;\n  border-radius: 2px;\n}\n\n/* 非微信代码块\n * 代码块不换行 display: -webkit-box !important;\n * 代码块换行 display: block;\n */\n#nice pre code {\n}\n\n/*\n * 表格内的单元格\n * 字体大小 font-size: 16px;\n * 边框 border: 1px solid #ccc;\n * 内边距 padding: 5px 10px;\n */\n#nice table tr th,\n#nice table tr td {\n}\n\n/* 脚注文字 */\n#nice .footnote-word {\n  color: #ff3502;\n  font-size: 16px;\n  line-height: 1.5;\n  font-weight: normal;\n}\n\n/* 脚注上标 */\n#nice .footnote-ref {\n  color: #ff3502;\n  font-weight: normal;\n}\n\n/* "参考资料"四个字 */\n#nice .footnotes-sep {\n}\n\n/* 参考资料编号 */\n#nice .footnote-num {\n}\n\n/* 参考资料文字 */\n#nice .footnote-item p { \n}\n\n/* 参考资料解释 */\n#nice .footnote-item p em {\n}\n\n/* 行间公式\n * 最大宽度 max-width: 300% !important;\n */\n#nice .block-equation svg {\n}\n\n/* 行内公式\n */\n#nice .inline-equation svg {  \n}',
    article:
      "https://mp.weixin.qq.com/s?__biz=MzIwNTA4NzI1Mw==&mid=2247485061&amp;idx=1&amp;sn=36047ec080d1daaf63d733d18e546ba7&source=41#wechat_redirect",
    html: null,
    exampleHtml: null,
    authorId: null,
    authorName: "画手",
    authorEmail: null,
    description: "Wechat Format的作者很懒，暂时没有描述",
    sort: null,
    checked: true,
    userThemeId: 63139,
    userThemeType: 0,
    fixThemeId: null,
    price: null,
    tmpPrice: null,
    isPublic: true,
    createTime: "2020-04-04T12:14:25.000+0800",
    updateTime: "2020-11-21T23:11:44.000+0800",
  },
  {
    themeId: "18",
    coinItemId: null,
    name: "极简黑",
    cover: "https://files.mdnice.com/pic/d4e91acf-c904-4f2d-9ddd-a6bd275bc54b.png",
    css:
      "/* 自定义样式，实时生效，浏览器实时缓存 */\n\n/* 全局属性\n * 页边距 padding: 30px;\n * 全文字体 font-family: ptima-Regular;\n * 英文换行 word-break: break-all;\n */\n #nice {\n  font-size:14px;\n  padding:10px;\n}\n\n/*图片下提示*/\n#nice figcaption{\n  font-size:12px;\n}\n#nice .imageflow-caption{\n  font-size:12px;\n}\n\n/* 段落，下方未标注标签参数均同此处\n * 上边距 margin-top: 5px;\n * 下边距 margin-bottom: 5px;\n * 行高 line-height: 26px;\n * 词间距 word-spacing: 3px;\n * 字间距 letter-spacing: 3px;\n * 对齐 text-align: left;\n * 颜色 color: #3e3e3e;\n * 字体大小 font-size: 16px;\n * 首行缩进 text-indent: 2em;\n */\n#nice p {\n  font-size:14px;\n}\n\n/* 一级标题 */\n#nice h1 {\n}\n\n/* 一级标题内容 */\n#nice h1 .content {\n}\n\n/* 一级标题前缀 */\n#nice h1 .prefix {\n}\n\n/* 一级标题后缀 */\n#nice h1 .suffix{\n}\n\n/* 二级标题 */\n#nice h2 {\n  \ttext-align:center;\n  \tposition:relative;\n    font-weight: bold;\n    color: black;\n    line-height: 1.1em;\n    padding-top: 12px;\n    padding-bottom: 12px;\n    margin:70px 30px 30px;\n    border: 1px solid #000;\n}\n\n#nice h2:before{\n  content: ' ';\n  float: left;\n  display: block;\n  width: 90%;\n  border-top: 1px solid #000;\n  height: 1px;\n  line-height: 1px;\n  margin-left: -5px;\n  margin-top: -17px;\n}\n#nice h2:after{\n  content: ' ';\n  float: right;\n  display: block;\n  width: 90%;\n  border-bottom: 1px solid #000;\n  height: 1px;\n  line-height: 1px;\n  margin-right: -5px;\n  margin-top: 16px;\n}\n/* 二级标题内容 */\n#nice h2 .content {\n  display: block;\n  -webkit-box-reflect: below 0em -webkit-gradient(linear,left top,left bottom, from(rgba(0,0,0,0)),to(rgba(255,255,255,0.1)));\n}\n#nice h2 strong {\n}\n/* 二级标题前缀 */\n#nice h2 .prefix {\n  display: block;\n  width: 3px;\n  margin: 0 0 0 5%;\n  height: 3px;\n  line-height: 3px;\n  overflow: hidden;\n  background-color: #000;\n  box-shadow:3px 0 #000,\n    0 3px #000,\n    -3px 0 #000,\n    0 -3px #000;\n}\n\n/* 二级标题后缀 */\n#nice h2 .suffix {\n  display: block;\n  width: 3px;\n  margin: 0 0 0 95%;\n  height: 3px;\n  line-height: 3px;\n  overflow: hidden;\n  background-color: #000;\n  box-shadow:3px 0 #000,\n    0 3px #000,\n    -3px 0 #000,\n    0 -3px #000;\n}\n\n/* 三级标题 */\n#nice h3 {\n  background-color:#000;\n  color:#fff;\n  padding:2px 10px;\n  width:fit-content;\n  font-size:17px;\n  margin:60px auto 10px;\n}\n#nice h3 strong {\n  color:#fff;\n}\n\n/* 三级标题内容 */\n#nice h3 .content {\n}\n\n/* 三级标题前缀 */\n#nice h3 .prefix {\n}\n\n/* 三级标题后缀 */\n#nice h3 .suffix {\n}\n\n/* 无序列表整体样式\n * list-style-type: square|circle|disc;\n */\n#nice ul {\n  list-style-type: square;\n}\n/* 无序二级列表\n */\n#nice ul li ul li{\n  list-style-type: circle;\n}\n\n/* 有序列表整体样式\n * list-style-type: upper-roman|lower-greek|lower-alpha;\n */\n#nice ol {\n}\n\n/* 列表内容，不要设置li\n */\n#nice li section {\n}\n\n/* 引用\n * 左边缘颜色 border-left-color: black;\n * 背景色 background: gray;\n */\n#nice .multiquote-1 {\n  border-left: 3px solid rgba(0, 0, 0, 0.65);\n  border-right: 1px solid rgba(0, 0, 0, 0.65);\n  background: rgb(249, 249, 249);\n}\n\n/* 引用文字 */\n#nice .multiquote-1 p {\n}\n\n/* 链接 \n * border-bottom: 1px solid #009688;\n */\n#nice a {\n}\n\n/* 加粗 */\n#nice strong {\n}\n\n/* 斜体 */\n#nice em {\n}\n\n/* 加粗斜体 */\n#nice em strong {\n}\n\n/* 删除线 */\n#nice del {\n}\n\n/* 分隔线\n * 粗细、样式和颜色\n * border-top: 1px solid #3e3e3e;\n */\n#nice hr {\n}\n\n/* 图片\n * 宽度 width: 80%;\n * 居中 margin: 0 auto;\n * 居左 margin: 0 0;\n */\n#nice img {\n  box-shadow: rgba(170, 170, 170, 0.48) 0px 0px 6px 0px;\n  border-radius:4px;\n  margin-top:10px;\n}\n/* 行内代码 */\n#nice p code, #nice li code {\n  color:#ff6441;\n}\n\n/* 非微信代码块\n * 代码块不换行 display: -webkit-box !important;\n * 代码块换行 display: block;\n */\n#nice pre.custom {\n  box-shadow: rgba(170, 170, 170, 0.48) 0px 0px 6px 0px;\n  max-width: 100%;\n  border-radius:4px;\n  margin: 10px auto 0 auto;\n}\n#nice pre code {\n}\n\n/*\n * 表格内的单元格\n * 字体大小 font-size: 16px;\n * 边框 border: 1px solid #ccc;\n * 内边距 padding: 5px 10px;\n */\n#nice table tr th,\n#nice table tr td {\n  font-size:14px;\n}\n\n/* 脚注文字 */\n#nice .footnote-word {\n}\n\n/* 脚注上标 */\n#nice .footnote-ref {\n}\n\n/* \"参考资料\"四个字 \n * 内容 content: \"参考资料\";\n */\n#nice .footnotes-sep {\n  font-size: 14px;\n  color: #888;\n  border-top: 1px solid #eee;\n  padding: 30px 0 10px 0px;\n  background-color: transparent;\n  margin: 0;\n  width: 100%;\n}\n#nice .footnotes-sep:before {\n  content:'参考资料';\n}\n#nice .footnotes{\n  border-left:5px solid #eee;\n  padding-left:10px;\n}\n\n/* 参考资料编号 */\n#nice .footnote-num {\n  font-size:14px;\n  color:#999;\n}\n\n/* 参考资料文字 */\n#nice .footnote-item p { \n  font-size:14px;\n  color:#999;\n}\n\n/* 参考资料解释 */\n#nice .footnote-item p em {\n  font-size:14px;\n  color:#999;\n}\n\n/* 行间公式\n * 最大宽度 max-width: 300% !important;\n */\n#nice .block-equation svg {\n}\n\n/* 行内公式\n */\n#nice .inline-equation svg {  \n}\n/* 文章结尾 */\n#nice:after{\n  content:'- END -';\n  font-size:15px;\n  display:block;\n  text-align:center;\n  margin-top:50px;\n  color:#999;\n  border-bottom:1px solid #eee;\n}\n\n/*滑动幻灯片*/\n#nice .imageflow-layer1 img{\n  margin:0;\n  box-shadow: none;\n  border-radius: 0;\n}\n",
    article: "https://mp.weixin.qq.com/s/6UQmAhyXQY6AaYcyd1npIg",
    html: null,
    exampleHtml: null,
    authorId: null,
    authorName: "小鱼",
    authorEmail: null,
    description: "公众号自律神仙ScarSu同款~",
    sort: null,
    checked: true,
    userThemeId: 57065,
    userThemeType: 0,
    fixThemeId: null,
    price: null,
    tmpPrice: null,
    isPublic: true,
    createTime: "2020-06-24T22:54:03.000+0800",
    updateTime: "2020-11-21T23:11:44.000+0800",
  },
  {
    themeId: "11",
    coinItemId: null,
    name: "山吹",
    cover: "https://files.mdnice.com/pic/2d041c6f-564b-4392-9636-9998f2b056bb.png",
    css:
      '/*自定义样式，实时生效*/\n#nice {\n}\n\n#nice p {\n\tmargin: 0 0 20px;\n\tpadding: 0;\n\tline-height: 1.8em;\n\tcolor: #3a3a3a;\n}\n\n/* 一级标题 */\n#nice h1 {\n  font-size: 2.1em;\n\tline-height: 1.1em;\n\tpadding-top: 16px;\n  padding-bottom: 10px;\n  margin-bottom: 4px;\n  border-bottom: 1px solid #c99833;\n}\n/* 一级标题内容 */\n#nice h1 .content {\n  color: #515151;\n  font-weight: 700;\n}\n\n#nice h2, h3, h4, h5, h6 {\n line-height: 1.5em;\n margin-top: 2.2em;\n margin-bottom: 4px;\n}\n\n/* 一级标题修饰 请参考有实例的主题 */\n#nice h1:after {}\n\n/* 二级标题 */\n#nice h2 {\n margin-bottom: 35px;\n}\n\n/* 二级标题内容 */\n\n#nice h2 .content {\n  display: inline-block;\n  font-weight: bold;\n  background: linear-gradient(#fff 60%, #ffb11b 40%);\n  color: #515151;\n  padding: 2px 13px 2px;\n  margin-right: 3px;\n  height: 50%;\n}\n\n/* 二级标题修饰 请参考有实例的主题 */\n#nice h2:after {}\n\n/* 三级标题 */\n#nice h3 {\n  line-height: 1.4;\n  padding-top: 10px;\n  margin: 10px 0 5px;\n}\n\n/* 三级标题内容 */\n#nice h3 .content {\n  color: #515151;\n  font-weight: 700;\n font-size: 1.0em;\n  padding-left: 20px;\n  border-left: 3px solid #f9bf45;\n}\n\n/* 三级标题修饰 请参考有实例的主题 */\n#nice h3:after {}\n\n/* 引用\n* 左边缘颜色 border-left-color: black;\n* 背景色 background: gray;\n*/\n#nice .multiquote-1 {\n  border-left-color: #ffb11b;\n background: #fff5e3;\n}\n\n/* 引用文字 */\n#nice .multiquote-1 p {\n  color: #595959;\n}\n\n/* 链接 */\n#nice a {\n  border: none;\n  text-decoration: none;\n  color: #dda52d;\n}\n\n#nice a:hover {\n  color: #f9bf45;\n  text-decoration: underline;\n}\n\n/* 无序列表整体样式\n * list-style-type: square|circle|disc;\n */\n#nice ul {\n}\n\n/* 有序列表整体样式\n * list-style-type: upper-roman|lower-greek|lower-alpha;\n */\n#nice ol {\n}\n\n/* 列表内容，不要设置li\n */\n#nice li section {\n}\n\n/* 加粗 */\n#nice strong {}\n\n/* 斜体 */\n#nice em {}\n\n/* 加粗斜体 */\n#nice em strong {}\n\n/* 删除线 */\n#nice del {\n  color: #d19826;\n}\n\n/* 分隔线\n* 粗细、样式和颜色\n* border-top: 1px solid #3e3e3e;\n*/\n#nice hr {\n  border-top: 1px solid #f9bf45;\n  margin: 20px 0px;\n}\n\n/* 图片\n* 宽度 width: 80%;\n* 居中 margin: 0 auto;\n* 居左 margin: 0 0;\n*/\n#nice img {\n  width: 100%;\n border-radius: 5px;\n display: block;\n margin-bottom: 15px;\n height: auto;\n}\n\n/* 图片描述文字 */\n#nice figcaption {\n  color: #dda52d;\n  font-size: 14px;\n}\n\n/* 行内代码 */\n#nice p code, #nice li code {\n  color: #9b6e23;\n  background-color: #fff5e3;\n  padding: 3px;\n  margin: 3px;\n}\n\n/* 非微信代码块\n * 代码块不换行 display: -webkit-box !important;\n * 代码块换行 display: block;\n */\n#nice pre code {}\n\n/*\n * 表格内的单元格\n * 字体大小 font-size: 16px;\n * 边框 border: 1px solid #ccc;\n * 内边距 padding: 5px 10px;\n */\n#nice table tr th,\n#nice table tr td {\n  text-align: center;\n}\n\n/* 脚注文字 */\n#nice .footnote-word {\n  color: #ffb11b;\n  padding: 3px;\n}\n\n/* 脚注上标 */\n#nice .footnote-ref {\n  color: #dda52d;\n  margin: 2px;\n  padding: 3px;\n}\n\n/* "参考资料"四个字 \n * 内容 content: "参考资料";\n */\n#nice .footnotes-sep:before {\n  margin: 30px 0px 15px 0px;\n  font-weight: 800;\n}\n\n\n/* 参考资料编号 */\n#nice .footnote-num {\n}\n\n/* 参考资料文字 */\n#nice .footnote-item p { \n}\n\n/* 参考资料解释 */\n#nice .footnote-item p em {\n}\n\n/* 行间公式\n * 最大宽度 max-width: 300% !important;\n */\n#nice .block-equation svg {\n}\n\n/* 行内公式\n */\n#nice .inline-equation svg {  \n}\n\n/* 滑动图片\n */\n#nice .imageflow-img {\n  display: inline-block;\n  width:100%;\n  margin-bottom: 0;\n}',
    article: "",
    html: null,
    exampleHtml: null,
    authorId: null,
    authorName: "ElyhG",
    authorEmail: null,
    description: "山吹的作者很懒，暂时没有描述",
    sort: null,
    checked: true,
    userThemeId: 57684,
    userThemeType: 0,
    fixThemeId: null,
    price: null,
    tmpPrice: null,
    isPublic: true,
    createTime: "2020-04-04T12:14:53.000+0800",
    updateTime: "2020-11-21T23:11:44.000+0800",
  },
  {
    themeId: "6",
    coinItemId: null,
    name: "红绯",
    cover: "https://files.mdnice.com/pic/9f008265-8511-4f9c-aafd-87027c94bd58.png",
    css:
      '/*自定义样式，实时生效*/\n\n/* 全局属性\n * 页边距 padding:30px;\n * 全文字体 font-family:ptima-Regular;\n * 英文换行 word-break:break-all;\n */\n#nice {\n    font-family: Optima-Regular, Optima, PingFangSC-light, PingFangTC-light, "PingFang SC", Cambria, Cochin, Georgia, Times, "Times New Roman", serif;\n    padding: 5px;\n    font-size: 16px;\n    color: #353535;\n    word-spacing: 0.8px;\n    letter-spacing: 0.8px;\n    border-radius: 16px;\n}\n\n/* 段落，下方未标注标签参数均同此处\n   * 上边距 margin-top:5px;\n   * 下边距 margin-bottom:5px;\n   * 行高 line-height:26px;\n   * 词间距 word-spacing:3px;\n   * 字间距 letter-spacing:3px;\n   * 对齐 text-align:left;\n   * 颜色 color:#3e3e3e;\n   * 字体大小 font-size:16px;\n   * 首行缩进 text-indent:2em;\n   */\n#nice p {\n    line-height: 1.75;\n    margin: 0.8em 0;\n    font-size: 16px;\n    color: #353535;\n}\n\n/* 一级标题 */\n#nice h1 {\n    border-top: 2px solid rgb(248, 57, 41);\n    text-align: center;\n    font-size: 1.3em;\n}\n\n/* 一级标题内容 */\n#nice h1 .content {\n    display: inline-block;\n    font-weight: normal;\n    background: rgb(248, 57, 41);\n    color: #ffffff;\n    padding: 3px 10px 1px;\n    border-radius: 0 0 13px 13px;\n}\n\n/* 一级标题修饰 请参考有实例的主题 */\n#nice h1:after {}\n\n/* 二级标题 */\n#nice h2 {\n    text-align: left;\n    margin: 20px 10px 0px 0px;\n}\n\n/* 二级标题内容 */\n#nice h2 .content {\n    font-size: 18px;\n    font-weight: 700;\n    color: #222;\n    display: inline-block;\n    padding-left: 10px;\n    border-left: 5px solid rgb(248, 57, 41);\n}\n\n/* 二级标题修饰 请参考有实例的主题 */\n#nice h2:after {}\n\n/* 三级标题 */\n#nice h3 {}\n\n/* 三级标题内容 */\n#nice h3 .content {\n    font-size: 16px;\n    color: #222;\n}\n\n/* 三级标题修饰 请参考有实例的主题 */\n#nice h3:after {}\n\n/* 无序列表整体样式\n   * list-style-type: square|circle|disc;\n   */\n#nice ul {\n    color: #f83929;\n    font-size: 16px;\n}\n\n/* 有序列表整体样式\n   * list-style-type: upper-roman|lower-greek|lower-alpha;\n   */\n#nice ol {\n    color: #f83929;\n    font-size: 16px;\n}\n\n/* 列表内容，不要设置li\n   */\n#nice li section {\n    color: #353535;\n}\n\n/* 引用\n   * 左边缘颜色 border-left-color:black;\n   * 背景色 background:gray;\n   */\n#nice .multiquote-1 {\n    font-style: normal;\n    border-left: none;\n    padding: 15px 10px;\n    line-height: 1.75;\n    border-radius: 13px;\n    color: #353535;\n    background: #f5f5f5;\n}\n\n#nice .multiquote-1:before {\n    content: "“";\n    display: block;\n    font-size: 2em;\n    color: rgb(248, 57, 41);\n    font-family: Arial, serif;\n    line-height: 1em;\n    font-weight: 700;\n}\n\n/* 引用文字 */\n#nice .multiquote-1 p {\n    color: #353535;\n    font-size: 16px;\n    margin: 0 10px;\n    display: block;\n}\n\n#nice .multiquote-1:after {\n    content: "”";\n    float: right;\n    display: block;\n    font-size: 2em;\n    color: rgb(248, 57, 41);\n    font-family: Arial, serif;\n    line-height: 1em;\n    font-weight: 700;\n}\n\n/* 链接 \n* border-bottom: 1px solid #009688;\n*/\n#nice a {\n    color: rgb(248, 57, 41);\n    font-weight: 400;\n    border-bottom: 1px solid rgb(248, 57, 41);\n\n}\n\n/* 加粗 */\n#nice strong {\n    font-weight: 700;\n    color: rgb(248, 57, 41);\n}\n\n/* 斜体 */\n#nice em {\n    color: rgb(248, 57, 41);\n}\n\n/* 加粗斜体 */\n#nice em strong {\n    color: rgb(248, 57, 41);\n}\n\n/* 删除线 */\n#nice del {}\n\n/* 分隔线\n   * 粗细、样式和颜色\n   * border-top:1px solid #3e3e3e;\n   */\n#nice hr {\n    height: 1px;\n    padding: 0;\n    border: none;\n    border-top: medium solidid #333;\n    text-align: center;\n    background-image: linear-gradient(to right, rgba(248, 57, 41, 0), rgba(248, 57, 41, 0.75), rgba(248, 57, 41, 0));\n}\n\n/* 图片\n   * 宽度 width:80%;\n   * 居中 margin:0 auto;\n   * 居左 margin:0 0;\n   */\n#nice figure {\n    border-radius: 16px;\n    overflow: hidden;\n}\n\n#nice figure a img {\n    border-radius: 16px;\n    width: 100%;\n    max-width: 100%;\n}\n\n#nice img {\n    border-radius: 6px;\n    display: block;\n    margin: 20px auto;\n    max-width: 95%;\n    object-fit: contain;\n}\n\n/* 图片描述文字 */\n#nice figcaption {\n    display: block;\n    font-size: 12px;\n}\n\n/* 行内代码 */\n#nice p code,\n#nice li code {\n    color: rgb(271, 93, 108);\n}\n\n/* 非微信代码块\n   * 代码块不换行 display:-webkit-box !important;\n   * 代码块换行 display:block;\n   */\n#nice pre code {}\n\n/*\n   * 表格内的单元格\n   * 字体大小 font-size: 16px;\n   * 边框 border: 1px solid #ccc;\n   * 内边距 padding: 5px 10px;\n   */\n#nice table tr th,\n#nice table tr td {\n    font-size: 16px;\n    color: #645647;\n}\n\n#nice table tr th {\n    color: #353535;\n    background-color: #dbd9d8;\n}\n\n#nice .footnotes {\n    font-size: 16px;\n}\n\n/* 脚注文字 */\n#nice .footnote-word {\n    font-weight: normal;\n    color: #f83929;\n}\n\n/* 脚注上标 */\n#nice .footnote-ref {\n    font-weight: normal;\n    color: #f83929;\n}\n\n/*脚注链接样式*/\n#nice .footnote-item em {\n    font-size: 16px;\n    display: block;\n}\n\n/* "参考资料"四个字 \n  * 内容 content: "参考资料";\n  */\n#nice .footnotes-sep:before {\n    content: \'参考资料 \';\n    color: #f83929;\n    letter-spacing: 1px;\n    text-align: left;\n    display: block;\n    font-weight: 500;\n    padding-bottom: .1em;\n    border-bottom: 3px double #f83929;\n    font-size: 20px;\n}\n\n/* 参考资料编号 */\n#nice .footnote-num {\n    color: #f83929;\n}\n\n/* 参考资料文字 */\n#nice .footnote-item p {\n    font-weight: 400;\n    color: #f83929;\n}\n\n/* 参考资料解释 */\n#nice .footnote-item p em {\n    font-weight: 400;\n    font-size: 14px;\n    color: #353535;\n}\n\n/* 行间公式\n  * 最大宽度 max-width: 300% !important;\n  */\n#nice .block-equation svg {\n    color: #353535;\n}\n\n/* 行内公式\n  */\n#nice .inline-equation svg {\n    color: #353535;\n}\n\n/* 滑动图片\n   */\n#nice .imageflow-img {\n    display: inline-block;\n    width: 100%;\n    margin-bottom: 0;\n}',
    article: "",
    html: null,
    exampleHtml: null,
    authorId: null,
    authorName: "HeyRain",
    authorEmail: null,
    description: "红绯的作者很懒，暂时没有描述",
    sort: null,
    checked: true,
    userThemeId: 16968,
    userThemeType: 0,
    fixThemeId: null,
    price: null,
    tmpPrice: null,
    isPublic: true,
    createTime: "2020-04-04T12:14:19.000+0800",
    updateTime: "2020-11-21T23:11:44.000+0800",
  },
  {
    themeId: "5",
    coinItemId: null,
    name: "绿意",
    cover: "https://files.mdnice.com/pic/02f3f593-3380-4aa6-9d90-6e2b6f276558.png",
    css:
      '/* 全局属性\n * 页边距 padding: 30px;\n * 全文字体 font-family: ptima-Regular;\n * 英文换行 word-break: break-all;\n */\n#nice {\n  font-size: 15px;\n  letter-spacing: 0.05em;\n  color:#595959\n}\n\n/* 段落，下方未标注标签参数均同此处\n * 上边距 margin-top: 5px;\n * 下边距 margin-bottom: 5px;\n * 行高 line-height: 26px;\n * 词间距 word-spacing: 3px;\n * 字间距 letter-spacing: 3px;\n * 对齐 text-align: left;\n * 颜色 color: #3e3e3e;\n * 字体大小 font-size: 16px;\n * 首行缩进 text-indent: 2em;\n */\n#nice p {\n  margin: 1em 4px;\n}\n\n/* 一级标题 */\n#nice h1 {\n  margin: 1.2em 0 1em;\n  padding: 0;\n  font-weight: bold;\n  color:#35b378;\n}\n\n/* 一级标题内容 */\n#nice h1 .content {\n}\n\n/* 一级标题修饰 请参考有实例的主题 */\n#nice h1:after {\n}\n\n/* 二级标题 */\n#nice h2 {\n  bmin-height: 32px;\n  line-height: 32px;\n  border-bottom: solid 1px #000000;\n  color: #35b378;\n  display: inline-block;\n  border-bottom-width: 0px;\n  border-bottom-style: solid;\n  border-color: #35b378;\n  padding-top: 5px;\n  padding-right: 0.5em;\n  padding-left: 0.5em;\n  font-size: 23px;\n  margin: 1em 0 0rem 0;\n  padding: 0.5em 0;\n  text-align: leftt;\n  font-weight: bold;\n}\n\n/* 二级标题内容 */\n#nice h2 .content {\n}\n\n/* 二级标题修饰 请参考有实例的主题 */\n#nice h2:after {\n}\n\n/* 三级标题 */\n#nice h3 {\n  margin: 1.2em 0 1em;\n  padding: 0;\n  font-weight: bold;\n  color: #35b378;\n}\n\n/* 三级标题内容 */\n#nice h3 .content {\n}\n\n/* 三级标题修饰 请参考有实例的主题 */\n#nice h3:after {\n}\n\n/* 无序列表整体样式\n * list-style-type: square|circle|disc;\n */\n#nice ul {\n}\n\n/* 有序列表整体样式\n * list-style-type: upper-roman|lower-greek|lower-alpha;\n */\n#nice ol {\n}\n\n/* 列表内容，不要设置li\n */\n#nice li section {\n  margin: 10px 0;\n}\n\n/* 引用\n * 左边缘颜色 border-left-color: black;\n * 背景色 background: gray;\n */\n#nice .multiquote-1 {\n  margin: 10px 5px;\n  border-left: 3px solid #35b378;\n  border-right: 0px solid #35b378;\n  color: #616161;\n  quotes: none;\n  background: #FBF9FD\n}\n\n/* 引用文字 */\n#nice .multiquote-1 p {\n}\n\n/* 链接 \n * border-bottom: 1px solid #009688;\n */\n#nice a {\n  color: #35b378;\n  border-bottom: 1px solid #35b378;\n}\n\n/* 加粗 */\n#nice strong {\n  color:#35b378;\n}\n\n/* 斜体 */\n#nice em {\n}\n\n/* 加粗斜体 */\n#nice em strong {\n}\n\n/* 删除线 */\n#nice del {\n}\n\n/* 分隔线\n * 粗细、样式和颜色\n * border-top: 1px solid #3e3e3e;\n */\n#nice hr {\n  border: 1px solid #35b378;\n  margin: 1.5em auto;\n}\n\n/* 图片\n * 宽度 width: 80%;\n * 居中 margin: 0 auto;\n * 居左 margin: 0 0;\n */\n#nice img {\n}\n\n/* 图片描述文字 */\n#nice figcaption {\n}\n\n/* 行内代码 */\n#nice p code, #nice li code {\n  color: #35b378;\n}\n\n/* 非微信代码块\n * 代码块不换行 display: -webkit-box !important;\n * 代码块换行 display: block;\n */\n#nice pre code {\n}\n\n/*\n * 表格内的单元格\n * 字体大小 font-size: 16px;\n * 边框 border: 1px solid #ccc;\n * 内边距 padding: 5px 10px;\n */\n#nice table tr th,\n#nice table tr td {\n}\n\n/* 脚注文字 */\n#nice .footnote-word {\n  color: #35b378;\n}\n\n/* 脚注上标 */\n#nice .footnote-ref {\n  color: #35b378;\n}\n\n/* "参考资料"四个字 \n * 内容 content: "参考资料";\n */\n#nice .footnotes-sep:before {\n}\n\n/* 参考资料编号 */\n#nice .footnote-num {\n}\n\n/* 参考资料文字 */\n#nice .footnote-item p { \n}\n\n/* 参考资料解释 */\n#nice .footnote-item p em {\n}\n\n/* 行间公式\n * 最大宽度 max-width: 300% !important;\n */\n#nice .block-equation svg {\n}\n\n/* 行内公式\n */\n#nice .inline-equation svg {  \n}',
    article: "https://mp.weixin.qq.com/s/gpancJ62Dkd4ccXzFg2g5Q",
    html: null,
    exampleHtml: null,
    authorId: null,
    authorName: "夜尽天明",
    authorEmail: null,
    description: "绿意的作者很懒，暂时没有描述",
    sort: null,
    checked: true,
    userThemeId: 16972,
    userThemeType: 0,
    fixThemeId: null,
    price: null,
    tmpPrice: null,
    isPublic: true,
    createTime: "2020-04-04T12:14:12.000+0800",
    updateTime: "2020-11-21T23:11:44.000+0800",
  },
  {
    themeId: "4",
    coinItemId: null,
    name: "嫩青",
    cover: "https://files.mdnice.com/pic/94cff81b-a086-46aa-a70e-1b9771b67cfc.png",
    css:
      '/* 全局属性\n * 页边距 padding: 30px;\n * 全文字体 font-family: ptima-Regular;\n * 英文换行 word-break: break-all;\n */\n#nice {\n}\n\n/* 段落，下方未标注标签参数均同此处\n * 上边距 margin-top: 5px;\n * 下边距 margin-bottom: 5px;\n * 行高 line-height: 26px;\n * 词间距 word-spacing: 3px;\n * 字间距 letter-spacing: 3px;\n * 对齐 text-align: left;\n * 颜色 color: #3e3e3e;\n * 字体大小 font-size: 16px;\n * 首行缩进 text-indent: 2em;\n */\n#nice p {\n  color: rgb(89,89,89);\n}\n\n/* 一级标题 */\n#nice h1 {\n  color: rgb(89,89,89);\n}\n\n/* 一级标题内容 */\n#nice h1 .content {\n}\n\n/* 一级标题修饰 请参考有实例的主题 */\n#nice h1:after {\n}\n\n/* 二级标题 */\n#nice h2 {\n  border-bottom: 2px solid rgb(89,89,89);\n  margin-bottom: 30px;\n  color: rgb(89,89,89);\n}\n\n/* 二级标题内容 */\n#nice h2 .content {\n  font-size: 22px;\n  display: inline-block;\n  border-bottom: 2px solid rgb(89,89,89);\n}\n\n/* 二级标题修饰 请参考有实例的主题 */\n#nice h2:after {\n}\n\n/* 三级标题 */\n#nice h3 {\n  color: rgb(89,89,89);\n}\n\n/* 三级标题内容 */\n#nice h3 .content {\n}\n\n/* 三级标题修饰 请参考有实例的主题 */\n#nice h3:after {\n}\n\n/* 无序列表整体样式\n * list-style-type: square|circle|disc;\n */\n#nice ul {\n}\n\n/* 有序列表整体样式\n * list-style-type: upper-roman|lower-greek|lower-alpha;\n */\n#nice ol {\n}\n\n/* 列表内容，不要设置li\n */\n#nice li section {\n}\n\n/* 引用\n* 左边缘颜色 border-left-color: black;\n* 背景色 background: gray;\n*/\n#nice .multiquote-1 {\n  font-style: normal;\n  padding: 10px;\n  position: relative;\n  line-height: 1.8;\n  text-indent: 0;\n  border: none;\n  color: #888;\n}\n\n#nice .multiquote-1:before {\n  content: "“";\n  display: inline;\n  color: #555555;\n  font-size: 4em;\n  font-family: Arial, serif;\n  line-height: 1em;\n  font-weight: 700;\n}\n\n/* 引用文字 */\n#nice .multiquote-1 p {\n  display: inline;\n}\n\n/* 链接 \n * border-bottom: 1px solid #009688;\n */\n#nice a {\n  color: rgb(71, 193, 168);\n  border-bottom: 1px solid rgb(71, 193, 168);\n}\n\n/* 加粗 */\n#nice strong {\n  color: rgb(71, 193, 168);\n}\n\n/* 斜体 */\n#nice em {\n  color: rgb(71, 193, 168);\n}\n\n/* 加粗斜体 */\n#nice em strong {\n  color: rgb(71, 193, 168);\n}\n\n/* 删除线 */\n#nice del {\n}\n\n/* 分隔线\n* 粗细、样式和颜色\n* border-top: 1px solid #3e3e3e;\n*/\n#nice hr {\n}\n\n/* 图片\n* 宽度 width: 80%;\n* 居中 margin: 0 auto;\n* 居左 margin: 0 0;\n*/\n#nice img {\n}\n\n/* 图片描述文字 */\n#nice figcaption {\n}\n\n/* 行内代码 */\n#nice p code, #nice li code {\n  color: rgb(71, 193, 168);\n}\n\n/* 非微信代码块\n * 代码块不换行 display: -webkit-box !important;\n * 代码块换行 display: block;\n */\n#nice pre code {\n}\n\n/*\n * 表格内的单元格\n * 字体大小 font-size: 16px;\n * 边框 border: 1px solid #ccc;\n * 内边距 padding: 5px 10px;\n */\n#nice table tr th,\n#nice table tr td {\n}\n\n/* 脚注文字 */\n#nice .footnote-word {\n  color: rgb(71, 193, 168);\n}\n\n/* 脚注上标 */\n#nice .footnote-ref {\n  color: rgb(71, 193, 168);\n}\n\n#nice .footnote-item em {\n  color: black;\n}\n\n/* "参考资料"四个字 \n * 内容 content: "参考资料";\n */\n#nice .footnotes-sep:before {\n}\n\n/* 参考资料编号 */\n#nice .footnote-num {\n}\n\n/* 参考资料文字 */\n#nice .footnote-item p { \n}\n\n/* 参考资料解释 */\n#nice .footnote-item p em {\n}\n\n/* 行间公式\n * 最大宽度 max-width: 300% !important;\n */\n#nice .block-equation svg {\n}\n\n/* 行内公式\n */\n#nice .inline-equation svg {  \n}',
    article: null,
    html: null,
    exampleHtml: null,
    authorId: null,
    authorName: "画手",
    authorEmail: null,
    description: "嫩青的作者很懒，暂时没有描述",
    sort: null,
    checked: true,
    userThemeId: 16971,
    userThemeType: 0,
    fixThemeId: null,
    price: null,
    tmpPrice: null,
    isPublic: true,
    createTime: "2020-04-04T12:14:06.000+0800",
    updateTime: "2020-11-21T23:11:44.000+0800",
  },
  {
    themeId: "3",
    coinItemId: null,
    name: "姹紫",
    cover: "https://files.mdnice.com/pic/e989865f-32c6-4201-a486-9f85fe7c2fab.png",
    css:
      '/* 全局属性\n * 页边距 padding: 30px;\n * 全文字体 font-family: ptima-Regular;\n * 英文换行 word-break: break-all;\n */\n#nice {\n  font-size: 15px;\n  letter-spacing: 0.05em;\n  color:#595959\n}\n\n/* 段落，下方未标注标签参数均同此处\n * 上边距 margin-top: 5px;\n * 下边距 margin-bottom: 5px;\n * 行高 line-height: 26px;\n * 词间距 word-spacing: 3px;\n * 字间距 letter-spacing: 3px;\n * 对齐 text-align: left;\n * 颜色 color: #3e3e3e;\n * 字体大小 font-size: 16px;\n * 首行缩进 text-indent: 2em;\n */\n#nice p {\n  margin: 1em 4px;\n}\n\n/* 一级标题 */\n#nice h1 {\n  margin: 1.2em 0 1em;\n  padding: 0;\n  font-weight: bold;\n  color:#773098;\n}\n\n/* 一级标题内容 */\n#nice h1 .content {\n}\n\n/* 一级标题修饰 请参考有实例的主题 */\n#nice h1:after {\n}\n\n/* 二级标题 */\n#nice h2 {\n  min-height: 32px;\n  line-height: 28px;\n  border-bottom: solid 1px #000000;\n  color: #773098;\n  display: inline-block;\n  border-bottom-width: 1px;\n  border-bottom-style: solid;\n  border-color: #773098;\n  padding-top: 5px;\n  padding-right: 0.5em;\n  padding-left: 0.5em;\n  margin-bottom: -3px;\n  font-size: 22px;\n  margin:1em auto;\n  padding: 0.5em 0;\n  text-align: center;\n  width: 85%;\n  font-weight: bold;\n  display: flex;\n  flex-direction: column;\n  justify-content: center;\n}\n\n/* 二级标题内容 */\n#nice h2 .content {\n}\n\n/* 二级标题修饰 请参考有实例的主题 */\n#nice h2:after {\n}\n\n/* 三级标题 */\n#nice h3 {\n  margin: 1.2em 0 1em;\n  padding: 0;\n  font-weight: bold;\n  color:#773098;\n}\n\n/* 三级标题内容 */\n#nice h3 .content {\n}\n\n/* 三级标题修饰 请参考有实例的主题 */\n#nice h3:after {\n}\n\n/* 无序列表整体样式\n * list-style-type: square|circle|disc;\n */\n#nice ul {\n}\n\n/* 有序列表整体样式\n * list-style-type: upper-roman|lower-greek|lower-alpha;\n */\n#nice ol {\n}\n\n/* 列表内容，不要设置li\n */\n#nice li section {\n  margin: 10px 0;\n}\n\n/* 引用\n * 左边缘颜色 border-left-color: black;\n * 背景色 background: gray;\n */\n#nice .multiquote-1 {\n  margin: 10px 5px;\n  border-left: 3px solid #9654B5;\n  border-right: 1px solid #9654B5;\n  color: #616161;\n  quotes: none;\n  background:#FBF9FD\n}\n\n/* 引用文字 */\n#nice .multiquote-1 p {\n}\n\n/* 链接 \n * border-bottom: 1px solid #009688;\n */\n#nice a {\n  color: #773098;\n  border-bottom: 1px solid #773098;\n}\n\n/* 加粗 */\n#nice strong {\n  color:#773098;\n}\n\n/* 斜体 */\n#nice em {\n}\n\n/* 加粗斜体 */\n#nice em strong {\n}\n\n/* 删除线 */\n#nice del {\n}\n\n/* 分隔线\n* 粗细、样式和颜色\n* border-top: 1px solid #3e3e3e;\n*/\n#nice hr {\n  border: 1px solid #773098;\n  margin: 1.5em auto;\n}\n\n/* 图片\n* 宽度 width: 80%;\n* 居中 margin: 0 auto;\n* 居左 margin: 0 0;\n*/\n#nice img {\n}\n\n/* 行内代码 */\n#nice p code, #nice li code {\n  color: #9654B5;\n}\n\n/* 非微信代码块\n * 代码块不换行 display: -webkit-box !important;\n * 代码块换行 display: block;\n */\n#nice pre code {\n}\n\n/*\n * 表格内的单元格\n * 字体大小 font-size: 16px;\n * 边框 border: 1px solid #ccc;\n * 内边距 padding: 5px 10px;\n */\n#nice table tr th,\n#nice table tr td {\n}\n\n/* 脚注文字 */\n#nice .footnote-word {\n  color: #773098;\n}\n\n/* 脚注上标 */\n#nice .footnote-ref {\n  color: #773098;\n}\n\n/* "参考资料"四个字 \n * 内容 content: "参考资料";\n */\n#nice .footnotes-sep:before {\n}\n\n/* 参考资料编号 */\n#nice .footnote-num {\n}\n\n/* 参考资料文字 */\n#nice .footnote-item p { \n}\n\n/* 参考资料解释 */\n#nice .footnote-item p em {\n}\n\n/* 行间公式\n * 最大宽度 max-width: 300% !important;\n */\n#nice .block-equation svg {\n}\n\n/* 行内公式\n */\n#nice .inline-equation svg {  \n}',
    article: null,
    html: null,
    exampleHtml: null,
    authorId: null,
    authorName: "一淼",
    authorEmail: null,
    description: "我喜欢极简风格晔喜欢这个紫色，清晰有力而且也很有魅力。也是做很多年设计师后，发现很好用的颜色。",
    sort: null,
    checked: true,
    userThemeId: 16970,
    userThemeType: 0,
    fixThemeId: null,
    price: null,
    tmpPrice: null,
    isPublic: true,
    createTime: "2020-04-04T12:14:00.000+0800",
    updateTime: "2023-04-10T12:27:01.000+0800",
  },
  {
    themeId: "1",
    coinItemId: null,
    name: "橙心",
    cover: "https://files.mdnice.com/pic/9322d897-85d5-4be1-9c9d-c392d4d39bff.png",
    css:
      '/* 全局属性\n * 页边距 padding: 30px;\n * 全文字体 font-family: ptima-Regular;\n * 英文换行 word-break: break-all;\n */\n#nice {\n}\n/* 段落，下方未标注标签参数均同此处\n * 上边距 margin-top: 5px;\n * 下边距 margin-bottom: 5px;\n * 行高 line-height: 26px;\n * 词间距 word-spacing: 3px;\n * 字间距 letter-spacing: 3px;\n * 对齐 text-align: left;\n * 颜色 color: #3e3e3e;\n * 字体大小 font-size: 16px;\n * 首行缩进 text-indent: 2em;\n */\n#nice p {\n}\n/* 一级标题 */\n#nice h1 {\n}\n/* 一级标题内容 */\n#nice h1 .content {\n}\n/* 一级标题修饰 请参考有实例的主题 */\n#nice h1:after {\n}\n/* 二级标题 */\n#nice h2 {\n  border-bottom: 2px solid rgb(239, 112, 96);\n  font-size: 1.3em;\n}\n/* 二级标题内容 */\n#nice h2 .content {\n  display: inline-block;\n  font-weight: bold;\n  background: rgb(239, 112, 96);\n  color: #ffffff;\n  padding: 3px 10px 1px;\n  border-top-right-radius: 3px;\n  border-top-left-radius: 3px;\n  margin-right: 3px;\n}\n/* 二级标题修饰 请参考有实例的主题 */\n#nice h2:after {\n  display: inline-block;\n  content: " ";\n  vertical-align: bottom;\n  border-bottom: 36px solid #efebe9;\n  border-right: 20px solid transparent;\n}\n/* 三级标题 */\n#nice h3 {\n}\n/* 三级标题内容 */\n#nice h3 .content {\n}\n/* 三级标题修饰 请参考有实例的主题 */\n#nice h3:after {\n}\n/* 无序列表整体样式\n * list-style-type: square|circle|disc;\n */\n#nice ul {\n}\n/* 有序列表整体样式\n * list-style-type: upper-roman|lower-greek|lower-alpha;\n */\n#nice ol {\n}\n/* 列表内容，不要设置li\n */\n#nice li section {\n}\n/* 引用\n * 左边缘颜色 border-left-color: black;\n * 背景色 background: gray;\n */\n#nice .multiquote-1 {\n  border-left-color: rgb(239, 112, 96);\n  background: #fff9f9;\n}\n/* 引用文字 */\n#nice .multiquote-1 p {\n}\n/* 链接 \n * border-bottom: 1px solid #009688;\n */\n#nice a {\n  color: rgb(239, 112, 96);\n  border-bottom: 1px solid rgb(239, 112, 96);\n}\n/* 加粗 */\n#nice strong {\n}\n/* 斜体 */\n#nice em {\n}\n/* 加粗斜体 */\n#nice em strong {\n}\n/* 删除线 */\n#nice del {\n}\n/* 分隔线\n * 粗细、样式和颜色\n * border-top: 1px solid #3e3e3e;\n */\n#nice hr {\n}\n/* 图片\n * 宽度 width: 80%;\n * 居中 margin: 0 auto;\n * 居左 margin: 0 0;\n */\n#nice img {\n}\n/* 图片描述文字 */\n#nice figcaption {\n}\n/* 行内代码 */\n#nice p code, #nice li code {\n  color: rgb(239, 112, 96);\n}\n/* 非微信代码块\n * 代码块不换行 display: -webkit-box !important;\n * 代码块换行 display: block;\n */\n#nice pre code {\n}\n/*\n * 表格内的单元格\n * 字体大小 font-size: 16px;\n * 边框 border: 1px solid #ccc;\n * 内边距 padding: 5px 10px;\n */\n#nice table tr th,\n#nice table tr td {\n}\n/* 脚注文字 */\n#nice .footnote-word {\n  color: #ff3502;\n}\n/* 脚注上标 */\n#nice .footnote-ref {\n  color: rgb(239, 112, 96);\n}\n/* "参考资料"四个字 \n * 内容 content: "参考资料";\n */\n#nice .footnotes-sep:before {\n}\n/* 参考资料编号 */\n#nice .footnote-num {\n}\n/* 参考资料文字 */\n#nice .footnote-item p { \n}\n/* 参考资料解释 */\n#nice .footnote-item p em {\n}\n/* 行间公式\n * 最大宽度 max-width: 300% !important;\n */\n#nice .block-equation svg {\n}\n/* 行内公式\n */\n#nice .inline-equation svg {  \n}',
    article:
      "https://mp.weixin.qq.com/s?__biz=MzIwNTA4NzI1Mw==&mid=2247485062&amp;idx=1&amp;sn=0eaa314bb165c71a8f57c8baf4226f57&source=41#wechat_redirect",
    html: null,
    exampleHtml: null,
    authorId: null,
    authorName: "zhning12",
    authorEmail: null,
    description: "橙心的作者很懒，暂时没有描述",
    sort: null,
    checked: true,
    userThemeId: 16969,
    userThemeType: 0,
    fixThemeId: null,
    price: null,
    tmpPrice: null,
    isPublic: true,
    createTime: "2020-04-04T09:57:55.000+0800",
    updateTime: "2020-11-21T23:11:44.000+0800",
  },
];
